services:
  postgres:
    image: postgres:16-alpine
    container_name: monew-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=monew_db

## 실행: docker-compose up -d