spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  batch:
    job:
      enabled: false # 서버가 켜질 때 배치가 자동으로 실행되는 것을 방지

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    com.codeit.monew: trace

external-api:
  naver:
    url: https://openapi.naver.com
    client-id: ${NAVER_CLIENT_ID:your_client_id}
    client-secret: ${NAVER_CLIENT_SECRET:your_client_secret}
