spring:
  flyway:
    enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100
  batch:
    job:
      enabled: false

external-api:
  naver:
    url: ${NAVER_API_URL:https://openapi.naver.com}
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

logging:
  level:
    root: info
    com.codeit.monew: info
