server:
  port: ${PORT:8080}

spring:
  application:
    name: P1_Monew

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: info