name: CI Pipeline

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: monew_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        # DB가 준비될 때까지 헬스체크 대기
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 1. 내 코드 가져오기 (Checkout)
        uses: actions/checkout@v3

      - name: 2. 자바(JDK) 17 설치 및 Gradle 캐시 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: 3. gradlew에 실행 권한 부여하기
        run: chmod +x gradlew

      - name: 4. 데이터베이스 연결 및 프로젝트 빌드 및 커버리지 검사하기 (테스트 실행)
        # 테스트 실행 후, 80% 룰(jacocoTestCoverageVerification)까지 검사!
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: monew_test
          DB_USER: user
          DB_PASSWORD: pass
        run: ./gradlew build jacocoTestCoverageVerification